// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:musix_trans/models/translation/translation.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlbumAdapter());
    registerAdapter(ArtistAdapter());
    registerAdapter(LineAdapter());
    registerAdapter(SpotyApiDataAdapter());
    registerAdapter(TranslationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlbumAdapter());
    registerAdapter(ArtistAdapter());
    registerAdapter(LineAdapter());
    registerAdapter(SpotyApiDataAdapter());
    registerAdapter(TranslationAdapter());
  }
}
